<a href="https://colab.research.google.com/github/taruvaid/Fourier-Neural-Operators/blob/main/pytorch_concepts.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
## Pytorch
# Deep learning primitives, neural network depth/width, activation functions and optimizers etc.
# autograd - automatic differentiation engine that enables backward pass of your model to be done through a single function call
# Tools to work at scale - TorchScript (serializable/optimizatble models), TorchServe (model serving solution),quantization
# Associated libraries/data for computer vision, audio and text data (Ex. torchvision etc.)
# Pytorch is written in C++
# Strong online/open source community

import torch
import numpy as np

**Tensors (multidimensional array)**

In [1]:
#Tensors are essentially multidimensional arrays (matrices)
z = torch.zeros([5,3]) # torch tensor
z_np = np.zeros([5,3]) # numpy array

print(z)
print(z.dtype)
print(z_np.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
torch.float32
float64


In [ ]:
z_int = torch.ones((2,3),dtype = int) #overriding default datatype to integer
print(z_int)

tensor([[1, 1, 1],
        [1, 1, 1]])


In [ ]:
# Seeding and pytorch's random number generator (PRND)

torch.manual_seed(2025)
z1 = torch.rand(2,3)
print("First random tensor")
print(z1)

z2 = torch.rand(2,3)
print("\nSecond random tensor (will be different from z1 because seed was not specified)")
print(z2)

#repeats value because of re-seed
torch.manual_seed(2025)
z3 = torch.rand(2,3)
print("\nThird random tensor (should match first one)")
print(z3)

# Further Reading -
# Pytorch Quick Tip: Reproducible Results and Deterministic Behavior : https://youtu.be/1SZocGaCAr8?feature=shared
# https://docs.pytorch.org/docs/stable/notes/randomness.html

First random tensor
tensor([[0.6850, 0.9355, 0.2900],
        [0.3991, 0.7470, 0.0215]])

Second random tensor (will be different from z1 because seed was not specified)
tensor([[0.0654, 0.7855, 0.3883],
        [0.6340, 0.9447, 0.4773]])

Third random tensor (should match first one)
tensor([[0.6850, 0.9355, 0.2900],
        [0.3991, 0.7470, 0.0215]])


In [14]:
# Mathematical operations using Tensors

tensor_1 = torch.rand (2,4) # tensor of random numbers from a uniform distribution on the interval [0,1)
tensor_2 = torch.rand (2,4)

# Addition happens elementwise. Both tensors must be of the same shape
tensor_add = tensor_1 + tensor_2

# Scalar multiplication happens elementwise
tensor_sm = tensor_1*10


print ("Tensor 1 :")
print(tensor_1)
print ("\nTensor 2 :")
print (tensor_2)
print ("\nTensor addition :")
print(tensor_add)
print ("\nScalar multiplication :")
print(tensor_sm)



Tensor 1 :
tensor([[0.6045, 0.9205, 0.1994, 0.4573],
        [0.9114, 0.3792, 0.2024, 0.4636]])

Tensor 2 :
tensor([[0.2031, 0.0702, 0.0649, 0.0324],
        [0.4256, 0.6001, 0.9934, 0.1961]])

Tensor addition :
tensor([[0.8076, 0.9907, 0.2643, 0.4897],
        [1.3371, 0.9793, 1.1958, 0.6597]])

Scalar multiplication :
tensor([[6.0447, 9.2050, 1.9937, 4.5725],
        [9.1143, 3.7924, 2.0243, 4.6360]])


In [51]:
#Several mathematical operations are available in pytorch...

r = (torch.rand(2,2)-0.5)*2 #random values between -1 and 1
print ("\nOriginal tensor :")
print(r)

# Absolute value
print ("\nAbsolute value :")
print(torch.abs(r))

print ("\nTrignometric functions :")
# Trignometric functions
print(torch.sin(r))

# Averages
print ("\nAverage value :")
print(torch.mean(r))

# Standard deviation and mean together
print ("\nStandard deviation with mean :")
print(torch.std_mean(r))

# Max and min
print ("\nMax & Min :")
print(torch.max(r))
print(torch.min(r))

# Determinant of a matrix
print ("\nDeterminants :")
print(torch.det(r))

# Matrix transpose
print ("\nMatrix transpose :")
print(torch.t(r))
# Singular value decomposition (Eigendecomposition)
print ("\nSingular value decomposition :")
print(torch.svd(r))


Original tensor :
tensor([[-0.4014, -0.1172],
        [ 0.1306,  0.5298]])

Absolute value :
tensor([[0.4014, 0.1172],
        [0.1306, 0.5298]])

Trignometric functions :
tensor([[-0.3907, -0.1170],
        [ 0.1302,  0.5054]])

Average value :
tensor(0.0355)

Standard deviation with mean :
(tensor(0.3948), tensor(0.0355))

Max & Min :
tensor(0.5298)
tensor(-0.4014)

Determinants :
tensor(-0.1974)

Matrix transpose :
tensor([[-0.4014,  0.1306],
        [-0.1172,  0.5298]])

Singular value decomposition :
torch.return_types.svd(
U=tensor([[-0.5134,  0.8581],
        [ 0.8581,  0.5134]]),
S=tensor([0.6052, 0.3261]),
V=tensor([[ 0.5257, -0.8507],
        [ 0.8507,  0.5257]]))
