<a href="https://colab.research.google.com/github/taruvaid/Fourier-Neural-Operators/blob/main/pytorch_concepts.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
## Pytorch
# Deep learning primitives, neural network depth/width, activation functions and optimizers etc.
# autograd - automatic differentiation engine that enables backward pass of your model to be done through a single function call
# Tools to work at scale - TorchScript (serializable/optimizatble models), TorchServe (model serving solution),quantization
# Associated libraries/data for computer vision, audio and text data (Ex. torchvision etc.)
# Pytorch is written in C++
# Strong online/open source community

import torch
import numpy as np

**Tensors (multidimensional array)**

In [ ]:
z = torch.zeros([5,3]) # z = torch.zeros(5,3)
z_np = np.zeros([5,3]) # numpy array
print(z)
print(z.dtype)
print(z_np.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32
float64


In [17]:
z_int = torch.ones((2,3),dtype = int) #overriding default datatype to integer
print(z_int)

tensor([[1, 1, 1],
        [1, 1, 1]])


In [19]:
# Seeding and pytorch's random number generator (PRND)

torch.manual_seed(2025)
z1 = torch.rand(2,3)
print("First random tensor")
print(z1)

z2 = torch.rand(2,3)
print("\nSecond random tensor (will be different from z1 because seed was not specified)")
print(z2)

#repeats value because of re-seed
torch.manual_seed(2025)
z3 = torch.rand(2,3)
print("\nThird random tensor (should match first one)")
print(z3)

# Further Reading -
# Pytorch Quick Tip: Reproducible Results and Deterministic Behavior : https://youtu.be/1SZocGaCAr8?feature=shared
# https://docs.pytorch.org/docs/stable/notes/randomness.html

First random tensor
tensor([[0.6850, 0.9355, 0.2900],
        [0.3991, 0.7470, 0.0215]])

Second random tensor (will be different from z1 because seed was not specified)
tensor([[0.0654, 0.7855, 0.3883],
        [0.6340, 0.9447, 0.4773]])

Third random tensor (should match first one)
tensor([[0.6850, 0.9355, 0.2900],
        [0.3991, 0.7470, 0.0215]])
